Repository justincase-jp/team-blog-hub, pull requests merged in 2021-12, with the labels that each got.

#1 feat: justincase-tech.com
  README.md
  site.config.ts
Labels: size/S

#2 feat: メンバーにkondeiを登録
  members.ts
  public/avatars/alexandria.jpg
  public/avatars/amanda.jpg
  public/avatars/catnose.jpg
  public/avatars/doe.jpg
  public/avatars/junji.jpg
  public/avatars/kondei.png
  public/avatars/naoko.jpg
Labels: size/M

#3 chore: add hiroga
  members.ts
Labels: size/S

#4 chore: update company logo
  public/logo.png
  public/logo.svg
  public/og.png
Labels: size/S

#5 feat: add takkyun
  members.ts
  public/avatars/takkyun.png
Labels: size/S

#6 chore: update deps
  next-env.d.ts
  next.config.mjs
  package.json
  scripts/posts.ts
  tsconfig.builder.json
  tsconfig.json
  yarn.lock
Labels: size/XXL

#7 chore: codeowners
  .github/CODEOWNERS
Labels: size/XS

#8 feat: add jict
  members.ts
  src/pages/about.tsx
Labels: size/S

#9 chore: add `diostray`
  members.ts
Labels: size/S

#10 jictのQiitaオーガナイゼーションのrssを追加
  members.ts
Labels: size/XS
